FROM python:3.10.12
EXPOSE 5000

WORKDIR /src/app
COPY ./docker/app/requirements.txt /src/requirements.txt
RUN apt install -y &&\
    apt update -y &&\
    pip install --upgrade pip &&\
    pip install -r ../requirements.txt

COPY ../../app /src/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]